Add new option -Qignore-c-std-not-allowed-with-cplusplus
To suppress option like -std=gnu99 defined in LOCAL_CFLAGS but get
passed for C++ compilation by both Android and NDK build system.
Since -std=gnu99 is C and not for C++, clang may error with message
reads (while g++ gives warning):

  error: invalid argument '-std=gnu99' not allowed with 'C++/ObjC++'

This flag is useful for "clang -fsyntax-only" to accept options originally
work for g++

Change-Id: I25bf360c7b127c03006684b18a321b6a65977fa3

Conflicts:
	include/clang/Driver/Options.td